
### get all tasks
GET http://localhost:3000/tasks
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWF0IjoxNjQ5MzM4MTU4LCJleHAiOjE2NDkzNDE3NTh9.jqOkkmy99ujmsgJB2NH92pYgq8qVkC0BxFb8-JJBpNo

### get tasks with filters
GET http://localhost:3000/tasks?status=OPEN


### get a task
GET http://localhost:3000/tasks/2a1c7503-6d27-4dda-bb39-b5b0361654d7


### create a new task
POST http://localhost:3000/tasks
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWF0IjoxNjQ5MzM4MTU4LCJleHAiOjE2NDkzNDE3NTh9.jqOkkmy99ujmsgJB2NH92pYgq8qVkC0BxFb8-JJBpNo

{
 "title": "test task",
 "description": "coucou"
}

### update task status
PATCH http://localhost:3000/tasks/6d1c07d4-c545-4e03-b00c-5576eed70f61/status
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWF0IjoxNjQ5MzM4MTU4LCJleHAiOjE2NDkzNDE3NTh9.jqOkkmy99ujmsgJB2NH92pYgq8qVkC0BxFb8-JJBpNo
content-type: application/json

{
 "status": "IN_PROGRESS"
}


### delete a task
DELETE http://localhost:3000/tasks/6d1c07d4-c545-4e03-b00c-5576eed70f61
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWF0IjoxNjQ5MzM4MTU4LCJleHAiOjE2NDkzNDE3NTh9.jqOkkmy99ujmsgJB2NH92pYgq8qVkC0BxFb8-JJBpNo
